version: "2"
services:
  gocqhttp:
    container_name: gocqhttp
    image: alpine
    volumes:
      - ".:/gocqhttp"
      - "../DicePP:/app/" # For send images in BotData
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    command: sh -c "cd ./gocqhttp && chmod 777 ./go-cqhttp && ./go-cqhttp"
networks:
  default:
    external:
      name: dice-net